UPDATE `oblast_prvky` SET `n1` = '561' WHERE `id` = '57';

UPDATE `oblast_prvky` SET `odk` = '562|688' WHERE `id` = '64';

UPDATE `oblast_prvky` SET `c3` = '0' WHERE `id` = '280';

UPDATE `oblast_prvky` SET `sm` = '1' WHERE `id` = '280';

UPDATE `oblast_prvky` SET `c3` = '0' WHERE `id` = '274';

UPDATE `oblast_prvky` SET `odk` = '788' WHERE `id` = '99';

UPDATE `oblast_prvky` SET `oznacenie` = 'S3' WHERE `id` = '19';
UPDATE `oblast_prvky` SET `oznacenie` = 'L3' WHERE `id` = '21';
UPDATE `oblast_prvky` SET `oznacenie` = 'MS' WHERE `id` = '26';
UPDATE `oblast_prvky` SET `oznacenie` = 'L' WHERE `id` = '32';
UPDATE `oblast_prvky` SET `oznacenie` = 'S1' WHERE `id` = '36';
UPDATE `oblast_prvky` SET `oznacenie` = 'L1' WHERE `id` = '38';
UPDATE `oblast_prvky` SET `oznacenie` = 'BS' WHERE `id` = '43';
UPDATE `oblast_prvky` SET `oznacenie` = 'S2' WHERE `id` = '52';
UPDATE `oblast_prvky` SET `oznacenie` = 'L2' WHERE `id` = '54';
UPDATE `oblast_prvky` SET `oznacenie` = 'MS' WHERE `id` = '71';
UPDATE `oblast_prvky` SET `oznacenie` = 'S1' WHERE `id` = '77';
UPDATE `oblast_prvky` SET `oznacenie` = 'Lc3' WHERE `id` = '79';
UPDATE `oblast_prvky` SET `oznacenie` = 'Sc3a' WHERE `id` = '81';
UPDATE `oblast_prvky` SET `oznacenie` = 'L3a' WHERE `id` = '83';
UPDATE `oblast_prvky` SET `oznacenie` = 'S1' WHERE `id` = '96';
UPDATE `oblast_prvky` SET `oznacenie` = 'L1' WHERE `id` = '98';
UPDATE `oblast_prvky` SET `oznacenie` = 'S' WHERE `id` = '107';
UPDATE `oblast_prvky` SET `oznacenie` = 'L' WHERE `id` = '118';
UPDATE `oblast_prvky` SET `oznacenie` = 'S2' WHERE `id` = '124';
UPDATE `oblast_prvky` SET `oznacenie` = 'L2' WHERE `id` = '126';
UPDATE `oblast_prvky` SET `oznacenie` = 'S4' WHERE `id` = '145';
UPDATE `oblast_prvky` SET `oznacenie` = 'L4' WHERE `id` = '147';
UPDATE `oblast_prvky` SET `oznacenie` = 'L5' WHERE `id` = '156';
UPDATE `oblast_prvky` SET `oznacenie` = 'S6' WHERE `id` = '160';
UPDATE `oblast_prvky` SET `oznacenie` = 'L6' WHERE `id` = '162';

UPDATE `oblast_prvky` SET `oznacenie` = 'S3' WHERE `id` = '173';
UPDATE `oblast_prvky` SET `oznacenie` = 'L3' WHERE `id` = '175';
UPDATE `oblast_prvky` SET `oznacenie` = 'PS' WHERE `id` = '178';
UPDATE `oblast_prvky` SET `oznacenie` = 'S8' WHERE `id` = '183';
UPDATE `oblast_prvky` SET `oznacenie` = 'L8' WHERE `id` = '185';
UPDATE `oblast_prvky` SET `oznacenie` = 'L' WHERE `id` = '189';
UPDATE `oblast_prvky` SET `oznacenie` = 'S1' WHERE `id` = '192';
UPDATE `oblast_prvky` SET `oznacenie` = 'L1' WHERE `id` = '194';
UPDATE `oblast_prvky` SET `oznacenie` = 'KS' WHERE `id` = '197';
UPDATE `oblast_prvky` SET `oznacenie` = 'OL' WHERE `id` = '203';
UPDATE `oblast_prvky` SET `oznacenie` = 'S5' WHERE `id` = '212';
UPDATE `oblast_prvky` SET `oznacenie` = 'L5' WHERE `id` = '214';
UPDATE `oblast_prvky` SET `oznacenie` = 'S3' WHERE `id` = '224';
UPDATE `oblast_prvky` SET `oznacenie` = 'L3' WHERE `id` = '226';
UPDATE `oblast_prvky` SET `oznacenie` = 'S3' WHERE `id` = '234';
UPDATE `oblast_prvky` SET `oznacenie` = 'L3' WHERE `id` = '236';
UPDATE `oblast_prvky` SET `oznacenie` = '1S' WHERE `id` = '243';
UPDATE `oblast_prvky` SET `oznacenie` = '1L' WHERE `id` = '250';
UPDATE `oblast_prvky` SET `oznacenie` = 'S1' WHERE `id` = '256';
UPDATE `oblast_prvky` SET `oznacenie` = 'L1' WHERE `id` = '258';
UPDATE `oblast_prvky` SET `oznacenie` = 'Sc1a' WHERE `id` = '260';
UPDATE `oblast_prvky` SET `oznacenie` = '1S' WHERE `id` = '266';
UPDATE `oblast_prvky` SET `oznacenie` = '1L' WHERE `id` = '272';
UPDATE `oblast_prvky` SET `oznacenie` = 'S1' WHERE `id` = '276';
UPDATE `oblast_prvky` SET `oznacenie` = 'L1' WHERE `id` = '278';

UPDATE `oblast_prvky` SET `oznacenie` = 'S' WHERE `id` = '282';
UPDATE `oblast_prvky` SET `oznacenie` = 'L' WHERE `id` = '290';
UPDATE `oblast_prvky` SET `oznacenie` = '2S' WHERE `id` = '294';
UPDATE `oblast_prvky` SET `oznacenie` = '2S' WHERE `id` = '301';
UPDATE `oblast_prvky` SET `oznacenie` = 'S2' WHERE `id` = '306';
UPDATE `oblast_prvky` SET `oznacenie` = 'L2' WHERE `id` = '308';
UPDATE `oblast_prvky` SET `oznacenie` = '2S' WHERE `id` = '317';
UPDATE `oblast_prvky` SET `oznacenie` = '2L' WHERE `id` = '323';
UPDATE `oblast_prvky` SET `oznacenie` = 'S2' WHERE `id` = '327';
UPDATE `oblast_prvky` SET `oznacenie` = 'L2' WHERE `id` = '329';
UPDATE `oblast_prvky` SET `oznacenie` = 'S4' WHERE `id` = '342';
UPDATE `oblast_prvky` SET `oznacenie` = 'Lc4' WHERE `id` = '344';
UPDATE `oblast_prvky` SET `oznacenie` = 'Sc4a' WHERE `id` = '346';
UPDATE `oblast_prvky` SET `oznacenie` = 'L4a' WHERE `id` = '348';
UPDATE `oblast_prvky` SET `oznacenie` = 'S4' WHERE `id` = '356';
UPDATE `oblast_prvky` SET `oznacenie` = 'L4' WHERE `id` = '358';
UPDATE `oblast_prvky` SET `oznacenie` = 'S6' WHERE `id` = '366';
UPDATE `oblast_prvky` SET `oznacenie` = 'Lc6' WHERE `id` = '368';
UPDATE `oblast_prvky` SET `oznacenie` = 'S8' WHERE `id` = '376';
UPDATE `oblast_prvky` SET `oznacenie` = 'Lc8' WHERE `id` = '378';

UPDATE `oblast_prvky` SET `oznacenie` = '3a' WHERE `id` = '82';
UPDATE `oblast_prvky` SET `oznacenie` = '6a' WHERE `id` = '166';
UPDATE `oblast_prvky` SET `oznacenie` = '1a' WHERE `id` = '261';
UPDATE `oblast_prvky` SET `oznacenie` = '4a' WHERE `id` = '347';
UPDATE `oblast_prvky` SET `oznacenie` = '4b' WHERE `id` = '351';
UPDATE `oblast_prvky` SET `oznacenie` = '6a' WHERE `id` = '372';

UPDATE `oblast_prvky` SET `c2` = '852' WHERE `id` = '101';

UPDATE `oblast_prvky` SET `c2` = '789' WHERE `id` = '127';

UPDATE `oblast_prvky` SET `oznacenie` = 'Se1' WHERE `id` = '34';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se6' WHERE `id` = '41';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se2' WHERE `id` = '50';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se7' WHERE `id` = '56';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se3' WHERE `id` = '60';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se5' WHERE `id` = '62';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se1' WHERE `id` = '93';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se6' WHERE `id` = '105';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se2' WHERE `id` = '120';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se5' WHERE `id` = '130';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se3' WHERE `id` = '143';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se4' WHERE `id` = '165';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se3' WHERE `id` = '220';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se4' WHERE `id` = '228';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se1' WHERE `id` = '252';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se7' WHERE `id` = '262';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se10' WHERE `id` = '264';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se2' WHERE `id` = '303';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se5' WHERE `id` = '310';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se6' WHERE `id` = '312';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se11' WHERE `id` = '315';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se8' WHERE `id` = '350';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se1' WHERE `id` = '360';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se9' WHERE `id` = '371';
UPDATE `oblast_prvky` SET `oznacenie` = 'Se4' WHERE `id` = '396';

UPDATE `oblast_prvky` SET
`n0` = '0'
WHERE `id_prvky_kluc` = '14' AND `oznacenie` IS NOT NULL;

UPDATE `oblast_prvky` SET `oznacenie` = '3BK' WHERE `id` = '25';
UPDATE `oblast_prvky` SET `oznacenie` = '1AK' WHERE `id` = '33';
UPDATE `oblast_prvky` SET `oznacenie` = '1BK' WHERE `id` = '42';
UPDATE `oblast_prvky` SET `oznacenie` = '2a' WHERE `id` = '49';
UPDATE `oblast_prvky` SET `oznacenie` = '2BK' WHERE `id` = '64';
UPDATE `oblast_prvky` SET `oznacenie` = '1AK' WHERE `id` = '92';
UPDATE `oblast_prvky` SET `oznacenie` = '1BK' WHERE `id` = '106';
UPDATE `oblast_prvky` SET `oznacenie` = '2AK' WHERE `id` = '119';
UPDATE `oblast_prvky` SET `oznacenie` = '2BK' WHERE `id` = '132';
UPDATE `oblast_prvky` SET `oznacenie` = '4AK' WHERE `id` = '142';
UPDATE `oblast_prvky` SET `oznacenie` = '3AK' WHERE `id` = '171';
UPDATE `oblast_prvky` SET `oznacenie` = '3BK' WHERE `id` = '177';
UPDATE `oblast_prvky` SET `oznacenie` = '1BK' WHERE `id` = '196';
UPDATE `oblast_prvky` SET `oznacenie` = '3a' WHERE `id` = '219';
UPDATE `oblast_prvky` SET `oznacenie` = '3b' WHERE `id` = '229';
UPDATE `oblast_prvky` SET `oznacenie` = '1BK' WHERE `id` = '242';
UPDATE `oblast_prvky` SET `oznacenie` = '1AK' WHERE `id` = '251';
UPDATE `oblast_prvky` SET `oznacenie` = '1BK' WHERE `id` = '265';
UPDATE `oblast_prvky` SET `oznacenie` = '1AK' WHERE `id` = '273';
UPDATE `oblast_prvky` SET `oznacenie` = '2AK' WHERE `id` = '291';
UPDATE `oblast_prvky` SET `oznacenie` = '2BK' WHERE `id` = '293';
UPDATE `oblast_prvky` SET `oznacenie` = '2AK' WHERE `id` = '302';
UPDATE `oblast_prvky` SET `oznacenie` = '2a' WHERE `id` = '311';
UPDATE `oblast_prvky` SET `oznacenie` = '2BK' WHERE `id` = '316';
UPDATE `oblast_prvky` SET `oznacenie` = '2AK' WHERE `id` = '324';
UPDATE `oblast_prvky` SET `oznacenie` = '2BK' WHERE `id` = '332';
UPDATE `oblast_prvky` SET `oznacenie` = '4a' WHERE `id` = '361';
UPDATE `oblast_prvky` SET `oznacenie` = '6' WHERE `id` = '399';

ALTER TABLE `oblast_prvky`
ADD `ts` int(11) NOT NULL DEFAULT '0' COMMENT 'traťový súhlas č.' AFTER `sm`;

UPDATE `oblast_prvky` SET `ts` = '0437' WHERE `id` = '45';
UPDATE `oblast_prvky` SET `ts` = '0712' WHERE `id` = '88';
UPDATE `oblast_prvky` SET `ts` = '0712' WHERE `id` = '89';
UPDATE `oblast_prvky` SET `ts` = '0712' WHERE `id` = '90';
UPDATE `oblast_prvky` SET `ts` = '0732' WHERE `id` = '109';
UPDATE `oblast_prvky` SET `ts` = '0732' WHERE `id` = '110';
UPDATE `oblast_prvky` SET `ts` = '0732' WHERE `id` = '111';
UPDATE `oblast_prvky` SET `ts` = '0732' WHERE `id` = '112';
UPDATE `oblast_prvky` SET `ts` = '0901' WHERE `id` = '115';
UPDATE `oblast_prvky` SET `ts` = '0901' WHERE `id` = '116';
UPDATE `oblast_prvky` SET `ts` = '0921' WHERE `id` = '134';
UPDATE `oblast_prvky` SET `ts` = '0921' WHERE `id` = '135';
UPDATE `oblast_prvky` SET `ts` = '0921' WHERE `id` = '136';
UPDATE `oblast_prvky` SET `ts` = '0921' WHERE `id` = '137';
UPDATE `oblast_prvky` SET `ts` = '0921' WHERE `id` = '138';
UPDATE `oblast_prvky` SET `ts` = '0946' WHERE `id` = '169';
UPDATE `oblast_prvky` SET `ts` = '01154' WHERE `id` = '199';
UPDATE `oblast_prvky` SET `ts` = '01154' WHERE `id` = '201';
UPDATE `oblast_prvky` SET `ts` = '01271' WHERE `id` = '246';
UPDATE `oblast_prvky` SET `ts` = '01271' WHERE `id` = '248';
UPDATE `oblast_prvky` SET `ts` = '01451' WHERE `id` = '288';
UPDATE `oblast_prvky` SET `ts` = '01460' WHERE `id` = '297';
UPDATE `oblast_prvky` SET `ts` = '01460' WHERE `id` = '299';
UPDATE `oblast_prvky` SET `ts` = '0421' WHERE  `id` = '25';
UPDATE `oblast_prvky` SET `ts` = '0421' WHERE  `id` = '33';
UPDATE `oblast_prvky` SET `ts` = '0437' WHERE  `id` = '42';
UPDATE `oblast_prvky` SET `ts` = '0626' WHERE  `id` = '64';
UPDATE `oblast_prvky` SET `ts` = '0712' WHERE  `id` = '92';
UPDATE `oblast_prvky` SET `ts` = '0921' WHERE  `id` = '132';
UPDATE `oblast_prvky` SET `ts` = '01154' WHERE  `id` = '142';
UPDATE `oblast_prvky` SET `ts` = '0946' WHERE  `id` = '171';
UPDATE `oblast_prvky` SET `ts` = '01451' WHERE  `id` = '177';
UPDATE `oblast_prvky` SET `ts` = '01154' WHERE  `id` = '196';
UPDATE `oblast_prvky` SET `ts` = '01271' WHERE  `id` = '242';
UPDATE `oblast_prvky` SET `ts` = '01271' WHERE  `id` = '251';
UPDATE `oblast_prvky` SET `ts` = '01302' WHERE  `id` = '265';
UPDATE `oblast_prvky` SET `ts` = '01302' WHERE  `id` = '273';
UPDATE `oblast_prvky` SET `ts` = '01451' WHERE  `id` = '291';
UPDATE `oblast_prvky` SET `ts` = '01460' WHERE  `id` = '293';
UPDATE `oblast_prvky` SET `ts` = '01460' WHERE  `id` = '302';
UPDATE `oblast_prvky` SET `ts` = '01491' WHERE  `id` = '316';
UPDATE `oblast_prvky` SET `ts` = '01491' WHERE  `id` = '324';
UPDATE `oblast_prvky` SET `ts` = '01507' WHERE  `id` = '332';
UPDATE `oblast_prvky` SET `ts` = '0421' WHERE `id` = '29';
UPDATE `oblast_prvky` SET `ts` = '01154' WHERE `id` = '200';
UPDATE `oblast_prvky` SET `ts` = '01271' WHERE `id` = '245';
UPDATE `oblast_prvky` SET `ts` = '01460' WHERE `id` = '296';
UPDATE `oblast_prvky` SET `ts` = '0421' WHERE `id` = '27';
UPDATE `oblast_prvky` SET `ts` = '0421' WHERE `id` = '28';
UPDATE `oblast_prvky` SET `ts` = '0421' WHERE `id` = '30';
UPDATE `oblast_prvky` SET `ts` = '01302' WHERE `id` = '268';
UPDATE `oblast_prvky` SET `ts` = '01302' WHERE `id` = '269';
UPDATE `oblast_prvky` SET `ts` = '01302' WHERE `id` = '270';
UPDATE `oblast_prvky` SET `ts` = '01302' WHERE `id` = '271';
UPDATE `oblast_prvky` SET `ts` = '01318' WHERE `id` = '283';
UPDATE `oblast_prvky` SET `ts` = '01318' WHERE `id` = '284';
UPDATE `oblast_prvky` SET `ts` = '01318' WHERE `id` = '285';
UPDATE `oblast_prvky` SET `ts` = '01491' WHERE `id` = '319';
UPDATE `oblast_prvky` SET `ts` = '01491' WHERE `id` = '320';
UPDATE `oblast_prvky` SET `ts` = '01491' WHERE `id` = '321';
UPDATE `oblast_prvky` SET `ts` = '01491' WHERE `id` = '322';
UPDATE `oblast_prvky` SET `ts` = '01507' WHERE `id` = '334';
UPDATE `oblast_prvky` SET `ts` = '01507' WHERE `id` = '335';
UPDATE `oblast_prvky` SET `ts` = '01507' WHERE `id` = '336';
UPDATE `oblast_prvky` SET `ts` = '437' WHERE `id` = '44';
UPDATE `oblast_prvky` SET `ts` = '626' WHERE `id` = '72';
UPDATE `oblast_prvky` SET `ts` = '732' WHERE `id` = '108';
UPDATE `oblast_prvky` SET `ts` = '901' WHERE `id` = '117';
UPDATE `oblast_prvky` SET `ts` = '1451' WHERE `id` = '179';
UPDATE `oblast_prvky` SET `ts` = '1135' WHERE `id` = '188';
UPDATE `oblast_prvky` SET `ts` = '1154' WHERE `id` = '198';
UPDATE `oblast_prvky` SET `ts` = '1154' WHERE `id` = '202';
UPDATE `oblast_prvky` SET `ts` = '1271' WHERE `id` = '244';
UPDATE `oblast_prvky` SET `ts` = '1271' WHERE `id` = '249';
UPDATE `oblast_prvky` SET `ts` = '1451' WHERE `id` = '289';
UPDATE `oblast_prvky` SET `ts` = '1460' WHERE `id` = '295';
UPDATE `oblast_prvky` SET `ts` = '1460' WHERE `id` = '300';
UPDATE `oblast_prvky` SET `ts` = '437' WHERE `id` = '46';
UPDATE `oblast_prvky` SET `ts` = '626' WHERE `id` = '73';
UPDATE `oblast_prvky` SET `ts` = '712' WHERE `id` = '87';
UPDATE `oblast_prvky` SET `ts` = '732' WHERE `id` = '113';
UPDATE `oblast_prvky` SET `ts` = '901' WHERE `id` = '114';
UPDATE `oblast_prvky` SET `ts` = '932' WHERE `id` = '139';
UPDATE `oblast_prvky` SET `ts` = '946' WHERE `id` = '168';
UPDATE `oblast_prvky` SET `ts` = '1135' WHERE `id` = '187';
UPDATE `oblast_prvky` SET `ts` = '1318' WHERE `id` = '286';
UPDATE `oblast_prvky` SET `ts` = '1507' WHERE `id` = '337';

ALTER TABLE `oblast`
ADD `image` varchar(100) COLLATE 'utf8_bin' NULL COMMENT 'Obrázok oblasti';